
on:
  schedule:
    - cron:  '0 12 * * *' # Every day at 12:00 (noon). Ref https://crontab.guru/examples.html
name: Scrape telegram bot API
jobs:
  build:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Scrape website
      run: python3 scrape.py

    - name: Open Pull Request
      uses: peter-evans/create-pull-request@v3.5.2
      with:
        commit-message: >
          Regenerate bot API docs.
        title: >
          Update bot API docs based on the latest changes
        body: >
          This is an automated PR. Please check the diff, and the action logs, to check for any funky behaviour.
        branch: automated/bot-api-update
        reviewers: PaulSonOfLars
        assignees: PaulSonOfLars
        labels: automated
        delete-branch: true
